### ISSUE TITLE
[Inflate] 통계뷰1 기능 구현

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#19]
## 💡 Issue
통계뷰1 - labeling 기능 구현

## 📝 todo
- [x] back btn 기능 구현
- [x] datepicker 기능 구현
- [x] 이미지 공유 구현
