### ISSUE TITLE
[Inflate] 메인뷰 기능 구현

### ISSUE THREAD

**Issue by s9hn** [Team-Beforeget/Beforeget-Android#20]
## 💡 Issue
· 메인뷰 기능 구현

## 📝 todo
- [x] recyclerview adapter 구현
- [x] 설정, 통계, 기록하기,전체보기 클릭이벤트 구현
- [x] 리사이클러 뷰 아이템 클릭리스너 구현
- [x] selected item intent 전달 구현
