### ISSUE TITLE
[Layout] 통계뷰4 구현

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#24]
## 💡 Issue
통계뷰4 (한 줄 평)

## 📝 todo
- [x] 전체뷰 구현
- [x] 카드뷰(앞면) 구현
- [x] 카드뷰(뒷면) 구현
- [x] 카드뷰 엠티뷰 구현
