### ISSUE TITLE
[Layout] 세훈 뷰 폰트 적용 

### ISSUE THREAD

**Issue by s9hn** [Team-Beforeget/Beforeget-Android#32]
## 💡 Issue

세훈 뷰 폰트 적용 

## 📝 todo

- [x] 메인 뷰 폰트 적용
- [x]  유형선택 뷰 폰트 적용
- [x] 아이템 리스트 뷰 폰트 적용
