### ISSUE TITLE
[Inflate] 글쓰기뷰 기능 구현

### ISSUE THREAD

**Issue by s9hn** [Team-Beforeget/Beforeget-Android#41]
## 💡 Issue

글쓰기뷰 기능 구현

## 📝 todo

- [x] 데이트 피커 구현
- [x] 별점 기능 구현
- [x] 바텀시트 구현
- [x] 칩그룹 구현
- [x] 클릭 리스너 구현
