### ISSUE TITLE
[Inflate] 기록항목추가 기능 구현

### ISSUE THREAD

**Issue by s9hn** [Team-Beforeget/Beforeget-Android#53]
## 💡 Issue

 기록항목추가 기능 구현

## 📝 todo

- [x] 각 버튼 리스너 구현
- [x] 글쓰기뷰로 인텐트 전달
- [x] 글쓰기뷰 리사이클러뷰에 타이틀과 에딧텍스트 넣기
