### ISSUE TITLE
[Remote] 통계뷰1 서버 연결

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#62]
## 💡 Issue

통계뷰1 라벨링 서버 연결

## 📝 todo

- [x] 통계뷰1 서버 통신
- [x] content 내용 \n을 기준으로 나눠서 넣기
- [x] img 받아서 이미지 영역 중앙에 두기 -> 레이아웃 변경 필요
