### ISSUE TITLE
[Remote] 통계뷰2 서버 연결

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#73]
## 💡 Issue

통계뷰2 그래프 서버 구현

## 📝 todo

- [x] 통계뷰2 서버 연결
- [x] 그래프 부분과 연결
- [x] 그래프 3M, 5M에 따른 연결
- [x] content 내용 \n을 기준으로 나눠서 넣기
