### ISSUE TITLE
[Chore] 이슈 템플릿 수정.

### ISSUE THREAD

**Issue by jinsu4755** [Team-Beforeget/Beforeget-Android#8]
## 💡 Issue
이슈 템플릿 일부 수정

## 📝 todo
- [x] 이슈 템플릿 제목과 설명 수정
- [x] 라벨 디폴트 추가
- [x] 각 부분 주석 추가
</br>

- [x] 버그 리포트 전용 이슈 템플릿 생성

---
해당 이슈는 프로젝트에 포함하지 않음.
