### ISSUE TITLE
[Remote] 통계뷰4 서버 연결

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#83]
## 💡 Issue

통계뷰4 한 줄 평 서버연결 

## 📝 todo

- [x] 전체뷰 서버 연결
- [x] 카드 앞면 서버 연결
- [x] 카드 뒷면 엠티뷰 서버 연결
- [x] 카드 뒷면 한 줄 평 서버 연결
