### ISSUE TITLE
[Remote] 통계뷰5 서버 연결

### ISSUE THREAD

**Issue by hjh1161514** [Team-Beforeget/Beforeget-Android#90]
## 💡 Issue

통계뷰5 한눈에 보기 서버 연결

## 📝 todo

- [x] 그래픽 서버 연결
- [x] 한 줄 평 서버 연결
- [x] 그래프 서버 연결
- [x] 랭킹 서버 연결
